
GET http://localhost:3001/api/notes
###
GET http://localhost:3001/api/notes/6682f9dcf43277f210f77a8c
###

PUT http://localhost:3001/api/notes/6682f9dcf43277f210f77a8c
Content-Type: application/json

{
  "content": "HTML",
  "mportant": false
}

###

DELETE http://localhost:3001/api/notes/6683287b1187926d25bb7eef
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "En",
  "mportant": true
}
